/** Card registry — balance pass */

export const CARD_PLAY_MODES = {
  INSTANT: "instant",
  FRIENDLY: "friendly",
  ENEMY: "enemy",
  EMPTY: "empty",
  F_EMPTY: "f_empty",
  F_F: "f_f",
  F_E: "f_e",
  F_E_ADJ: "f_e_adj",
  E_EMPTY: "e_empty",
  E_E_ADJ: "e_e_adj",
  F_F_ADJ: "f_f_adj",
  DIAGONAL: "diagonal",
  COLUMN: "column",
  ROW: "row",
  ANY_PIECE: "any_piece",
  ANY_SQUARE: "any_square",
  EMPTY_EMPTY: "empty_empty",
  DISCARD_PICK: "discard_pick",
};

export const CARD_REGISTRY = [
  { id: "nudge", name: "Nudge", desc: "Displace one of your pieces 1 square forward-diagonal onto an empty dark square.", rarity: "common", weight: 8, mode: "f_empty", effect: "nudge" },
  { id: "backstep", name: "Backstep", desc: "Move one of your pieces 1 square backward-diagonal onto an empty dark square.", rarity: "common", weight: 6, mode: "f_empty", effect: "backstep" },
  { id: "retreat", name: "Retreat", desc: "Grant a piece backward movement for 3 turns.", rarity: "common", weight: 6, mode: "friendly", effect: "retreat_3" },
  { id: "anchor", name: "Anchor", desc: "All your pieces cannot be moved by enemy cards for 2 turns (they still move on your turn).", rarity: "common", weight: 6, mode: "instant", effect: "anchor_2" },
  { id: "recall", name: "Recall", desc: "Return one of your pieces to an empty dark square on your back row (only playable when your back row has an empty space).", rarity: "common", weight: 6, mode: "f_empty", effect: "recall" },
  { id: "repel", name: "Repel", desc: "Push an adjacent enemy piece 1 square away if the landing square is empty.", rarity: "common", weight: 6, mode: "friendly", effect: "repel" },
  { id: "leapfrog", name: "Leapfrog", desc: "Jump your piece over a friendly piece to land on the empty square beyond.", rarity: "common", weight: 6, mode: "f_empty", effect: "leapfrog" },
  { id: "random_teleport", name: "Random Teleportation", desc: "Select a piece and it jumps to a random empty square. If it ends up on the back rank, it automatically becomes a king.", rarity: "common", weight: 6, mode: "friendly", effect: "random_teleport" },
  { id: "rally", name: "Rally", desc: "All pieces adjacent to a friendly piece gain retreat for 1 turn.", rarity: "common", weight: 6, mode: "friendly", effect: "rally" },
  { id: "coin_flip", name: "Coin Flip", desc: "50% destroy random enemy; 50% destroy random friendly.", rarity: "common", weight: 6, mode: "instant", effect: "coin_flip" },
  { id: "ignore", name: "Ignore", desc: "Jumps are optional for you this turn — only playable when capture is mandatory.", rarity: "common", weight: 6, mode: "instant", effect: "ignore" },
  { id: "iron_will", name: "Iron Will", desc: "A frozen or paralyzed friendly piece may move once (consumes debuff).", rarity: "common", weight: 5, mode: "friendly", effect: "iron_will" },
  { id: "demote", name: "Demote", desc: "Turn an enemy king back into a man (not on the back rank).", rarity: "common", weight: 6, mode: "enemy", effect: "demote" },
  { id: "quicksand", name: "Quicksand", desc: "Hidden trap on an empty dark square — the next piece to end a turn there is frozen (trap invisible until it triggers).", rarity: "common", weight: 6, mode: "empty", effect: "quicksand" },
  { id: "collapse", name: "Collapse", desc: "Remove one dark square from play for 3 turns; piece on it relocates.", rarity: "common", weight: 6, mode: "empty", effect: "collapse" },
  { id: "create_foe", name: "Create Foe", desc: "Spawn an enemy man on any empty dark square.", rarity: "common", weight: 5, mode: "empty", effect: "create_foe" },
  { id: "barrier", name: "Barrier", desc: "Summon a barrier on a dark square; enemies cannot enter it for 2 turn cycles (can be placed on occupied squares).", rarity: "common", weight: 5, mode: "empty", effect: "barrier" },
  { id: "duel", name: "Duel", desc: "Choose your piece and an adjacent enemy; both are destroyed unless shielded. If the enemy is frozen or paralyzed, your piece survives.", rarity: "common", weight: 5, mode: "f_e_adj", effect: "duel" },
  { id: "panic", name: "Panic", desc: "Force an enemy man to step backward on its owner's next turn if possible.", rarity: "common", weight: 5, mode: "enemy", effect: "panic" },
  { id: "shadow_swap", name: "Shadow Swap", desc: "Swap positions of two of your pieces.", rarity: "common", weight: 5, mode: "f_f", effect: "swap_friendly" },
  { id: "sidestep", name: "Sidestep", desc: "Skip 2 columns left or right along the same row to an empty dark square.", rarity: "common", weight: 6, mode: "f_empty", effect: "sidestep" },
  { id: "press", name: "Press", desc: "On opponent's next turn, they must move again after their normal move (extra step cannot capture).", rarity: "common", weight: 6, mode: "instant", effect: "press" },
  { id: "long_step", name: "Long Step", desc: "Move one of your pieces 2 squares diagonally if the path is clear (no capture).", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "long_step" },
  { id: "ward", name: "Ward", desc: "Shield a friendly piece for 1 turn — blocks one capture or spell hit (shields can be burned off).", rarity: "common", weight: 6, mode: "friendly", effect: "shield_1" },
  { id: "aegis", name: "Aegis", desc: "Shield a piece — it cannot be captured for 2 turns.", rarity: "uncommon", weight: 6, mode: "friendly", effect: "shield_2" },
  { id: "poison", name: "Poison", desc: "Mark an enemy — they die in 3 turns unless cleansed.", rarity: "uncommon", weight: 5, mode: "enemy", effect: "poison_3" },
  { id: "deflect", name: "Deflect", desc: "Hidden trap on a friendly piece — if a spell would destroy it within 2 turns, the closest enemy dies instead (captures still work; invisible until it triggers).", rarity: "uncommon", weight: 4, mode: "friendly", effect: "deflect_1" },
  { id: "stab", name: "Stab", desc: "Destroy an enemy on an adjacent forward diagonal.", rarity: "uncommon", weight: 6, mode: "diagonal", effect: "forward_bolt" },
  { id: "crown", name: "Royal Decree", desc: "Instantly crown one of your pieces (king movement).", rarity: "uncommon", weight: 4, mode: "friendly", effect: "crown" },
  { id: "teleport", name: "Blink", desc: "Teleport your piece to any empty dark square within 2 steps (Chebyshev).", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "blink_2" },
  { id: "landmine", name: "Landmine", desc: "Hidden trap on an empty dark square for 2 turns — destroys the next enemy to land there (invisible until it triggers).", rarity: "uncommon", weight: 5, mode: "empty", effect: "landmine" },
  { id: "offering", name: "Offering", desc: "Sacrifice one of your pieces to draw 2 cards; you may cast another spell immediately afterward.", rarity: "rare", weight: 3, mode: "friendly", effect: "offering" },
  { id: "backpedal", name: "Forced Retreat", desc: "Enemy can only move backward for 2 turns and cannot capture.", rarity: "uncommon", weight: 5, mode: "enemy", effect: "reverse_only_2" },
  { id: "root", name: "Root", desc: "Enemy cannot jump or capture on its next turn (can still step).", rarity: "uncommon", weight: 4, mode: "enemy", effect: "root_2" },
  { id: "sacrifice", name: "Sacrifice", desc: "Destroy one of your pieces to destroy any enemy (including kings).", rarity: "uncommon", weight: 4, mode: "f_e", effect: "sacrifice" },
  { id: "scatter", name: "Scatter", desc: "Push every piece adjacent to a square 1 step away radially.", rarity: "uncommon", weight: 4, mode: "empty", effect: "scatter" },
  { id: "displacement", name: "Displacement", desc: "Teleport one of your pieces to any empty dark square on your side of the board.", rarity: "rare", weight: 3, mode: "f_empty", effect: "displacement" },
  { id: "last_stand", name: "Last Stand", desc: "Hidden trap on a friendly piece — if it would be captured or destroyed, it survives with an ultra shield for 3 turns instead (invisible until it triggers; expires after 1 of your turn cycles if unused).", rarity: "uncommon", weight: 4, mode: "friendly", effect: "last_stand" },
  { id: "snowball", name: "Snowball", desc: "Freeze an enemy piece — it cannot move on its owner's next turn.", rarity: "common", weight: 6, mode: "any_piece", effect: "snowball" },
  { id: "dash", name: "Dash", desc: "Move one of your pieces 1 square forward-diagonally; destroy an enemy on that square.", rarity: "rare", weight: 3, mode: "f_empty", effect: "dash" },
  { id: "tangle", name: "Tangle", desc: "Swap two enemies and freeze both for 1 turn.", rarity: "rare", weight: 3, mode: "e_e", effect: "tangle" },
  { id: "bishops_mark", name: "Bishop's Mark", desc: "For 2 turns, a piece may slide along either diagonal over empty dark squares.", rarity: "rare", weight: 3, mode: "friendly", effect: "bishop_2" },
  { id: "rooks_mark", name: "Rook's Mark", desc: "For 2 turns, a piece may slide along a rank or file over empty dark squares.", rarity: "rare", weight: 3, mode: "friendly", effect: "rook_2" },
  { id: "magnet", name: "Magnet", desc: "Pull every enemy 2 squares away on a diagonal to an adjacent empty square next to your piece.", rarity: "epic", weight: 2, mode: "friendly", effect: "magnet" },
  { id: "call_forward", name: "Call Forward", desc: "Move an enemy up to 2 squares along a diagonal to an empty dark square with a clear path.", rarity: "rare", weight: 3, mode: "e_empty", effect: "call_forward" },
  { id: "blizzard", name: "Blizzard", desc: "Freeze all enemy men on a row of dark squares you choose.", rarity: "rare", weight: 3, mode: "row", effect: "blizzard" },
  { id: "bulwark", name: "Bulwark", desc: "All your pieces on one diagonal line gain shield for 2 turns.", rarity: "rare", weight: 3, mode: "friendly", effect: "bulwark" },
  { id: "darkness", name: "Darkness", desc: "Pieces on the 6 dark squares around a point cannot be captured, cannot capture, and cannot be targeted or destroyed for 2 turns.", rarity: "rare", weight: 3, mode: "empty", effect: "darkness" },
  { id: "stall", name: "Stall", desc: "Piece is immobile and invulnerable for 2 turns, then gains shield for 1 turn.", rarity: "rare", weight: 3, mode: "friendly", effect: "fortify" },
  { id: "hibernation", name: "Hibernation", desc: "Your piece sleeps immobile for 2 turns, then awakens with the Awoken Bear mark — it may move twice each turn forever after.", rarity: "rare", weight: 3, mode: "friendly", effect: "hibernation" },
  { id: "vengeance", name: "Vengeance", desc: "Hidden trap: the next enemy capture of your piece destroys the capturer; your piece survives 2 turns (blood counters), then dies. Expires after 2 of your turn cycles if unused.", rarity: "rare", weight: 3, mode: "instant", effect: "vengeance" },
  { id: "sanctuary", name: "Sanctuary", desc: "Friendly pieces on the target dark square and its 6 surrounding dark squares cannot be captured for 1 turn.", rarity: "rare", weight: 3, mode: "empty", effect: "sanctuary" },
  { id: "fusion", name: "Fusion", desc: "Merge two adjacent friendly men into one piece with the Awoken Bear mark — after each move with it, move again.", rarity: "rare", weight: 3, mode: "f_f_adj", effect: "fusion" },
  { id: "chameleon", name: "Chameleon", desc: "Copy any piece's movement tags on the board for 2 turns.", rarity: "rare", weight: 3, mode: "any_piece", effect: "chameleon" },
  { id: "cryo_bolt", name: "Cryo Bolt", desc: "Bolt along your diagonal: freezes a normal enemy, or destroys a frozen or paralyzed one (breaks shield).", rarity: "uncommon", weight: 3, mode: "diagonal", effect: "cryo_bolt" },
  { id: "last_king", name: "Last King", desc: "If you have only 1 piece, it becomes a king with shield for 2 turns.", rarity: "uncommon", weight: 4, mode: "instant", effect: "last_king" },
  { id: "quick_march", name: "Bonus Step", desc: "After your normal move, move the same piece again; either step may capture.", rarity: "epic", weight: 2, mode: "instant", effect: "quick_march" },
  { id: "shatter", name: "Shatter", desc: "Destroy any unshielded enemy. You cannot cast spells on your next turn.", rarity: "legendary", weight: 1, mode: "enemy", effect: "destroy_unshielded" },
  { id: "pyromancy", name: "Pyromancy", desc: "Ignite an enemy piece and one empty dark square — each burns for 2 turns (like poison, but fire). Burning tiles block enemy movement. You cannot cast spells on your next turn.", rarity: "legendary", weight: 1, mode: "e_empty", effect: "pyromancy" },
  { id: "bomb", name: "Bomb", desc: "Arm a friendly piece; when it moves, it explodes on adjacent squares (including itself).", rarity: "legendary", weight: 1, mode: "friendly", effect: "bomb" },
  { id: "shockwave", name: "Shockwave", desc: "Arm a friendly piece; when it moves, paralyze all adjacent pieces for 1 turn.", rarity: "epic", weight: 2, mode: "friendly", effect: "shockwave" },
  { id: "plague", name: "Plague", desc: "Infect one of your pieces and all adjacent pieces (yours and enemy). Wherever that seed moves, adjacent pieces become infected. Infected pieces die after 2 of their owner's turns.", rarity: "epic", weight: 2, mode: "friendly", effect: "plague" },
  { id: "chain_lightning", name: "Chain Lightning", desc: "Destroy up to 2 chained adjacent enemies from your piece.", rarity: "legendary", weight: 1, mode: "friendly", effect: "chain_lightning" },
  { id: "revive", name: "Revive", desc: "Return your most recently captured man to any empty dark square on your side of the board; no capture the turn it returns.", rarity: "legendary", weight: 1, mode: "empty", effect: "revive" },
  { id: "mind_control", name: "Mind Control", desc: "Convert an enemy man to your color for 2 of your turns, then it reverts to the enemy.", rarity: "epic", weight: 2, mode: "enemy", effect: "mind_control" },
  { id: "zombify", name: "Zombify", desc: "Curse an enemy man — when it dies, it rises as your man on that square. It cannot capture the turn it rises.", rarity: "epic", weight: 2, mode: "enemy", effect: "zombify" },
  { id: "cull", name: "Cull", desc: "Destroy the weakest enemy (non-king preferred).", rarity: "epic", weight: 2, mode: "instant", effect: "cull" },
  { id: "execution", name: "Execution", desc: "Destroy an enemy piece that has no legal moves.", rarity: "epic", weight: 2, mode: "enemy", effect: "execution" },
  { id: "snipe", name: "Snipe", desc: "Destroy an enemy 3+ squares away on a diagonal with nothing between.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "snipe" },
  { id: "backstab", name: "Backstab", desc: "Destroy an enemy behind your piece on a backward diagonal if adjacent.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "backstab" },
  { id: "blind", name: "Blind", desc: "Opponent cannot play cards on their next turn.", rarity: "rare", weight: 3, mode: "instant", effect: "blind" },
  { id: "confusion", name: "Confusion", desc: "On opponent's next turn, their move is chosen randomly.", rarity: "epic", weight: 2, mode: "instant", effect: "confusion" },
  { id: "extract", name: "Extract", desc: "Force your opponent to discard a random card from their hand.", rarity: "epic", weight: 2, mode: "instant", effect: "extract" },
  { id: "counterspell", name: "Counterspell", desc: "Hidden trap: the next enemy spell is cancelled when they cast it.", rarity: "epic", weight: 2, mode: "instant", effect: "counterspell" },
  { id: "deep_freeze", name: "Deep Freeze", desc: "Freeze every enemy on one diagonal through your piece for 2 turns.", rarity: "epic", weight: 2, mode: "diagonal", effect: "deep_freeze" },
  { id: "earthquake", name: "Earthquake", desc: "All pieces shift 1 square toward board center if possible.", rarity: "legendary", weight: 1, mode: "instant", effect: "earthquake" },
  { id: "berserk", name: "Berserk", desc: "Teleport one of your pieces anywhere except the enemy back rank. Landing on an enemy destroys it; you cannot capture this turn.", rarity: "legendary", weight: 1, mode: "f_empty", effect: "berserk" },
  { id: "hostile_swap", name: "Hostile Swap", desc: "Swap one of your pieces with an unshielded enemy.", rarity: "epic", weight: 2, mode: "f_e", effect: "hostile_swap" },
  { id: "purify", name: "Purify", desc: "Remove all debuffs from your pieces, including burn and freeze.", rarity: "epic", weight: 2, mode: "instant", effect: "purify" },
  { id: "trickster", name: "Trickster", desc: "Swap up to 6 random pieces (pieces on back ranks are unaffected).", rarity: "rare", weight: 3, mode: "instant", effect: "trickster" },
  { id: "bounty", name: "Bounty", desc: "Mark an enemy — when you capture it with a jump, draw 2 cards.", rarity: "epic", weight: 2, mode: "enemy", effect: "bounty" },
  { id: "link_fate", name: "Link Fate", desc: "Link two enemy pieces — when either is destroyed, the other dies too.", rarity: "epic", weight: 2, mode: "e_e", effect: "link_fate" },
  { id: "clone", name: "Clone", desc: "Duplicate one of your men on an adjacent empty square (original stays). The copy cannot capture, be captured, or be sacrificed until your next turn. Clones are destroyed instantly by freeze, poison, burn, or plague.", rarity: "epic", weight: 2, mode: "f_empty", effect: "clone" },
  { id: "constitution", name: "Constitution", desc: "Requires a king. Your kings cannot be destroyed by non-capture effects for 5 turns.", rarity: "epic", weight: 2, mode: "instant", effect: "constitution" },
  { id: "deport", name: "Deport", desc: "Send an enemy piece back to the square where it started the game; any piece already there is destroyed.", rarity: "epic", weight: 2, mode: "enemy", effect: "deport" },
  { id: "dominion", name: "Dominion", desc: "All your men may move backward for 2 turns.", rarity: "uncommon", weight: 4, mode: "instant", effect: "dominion" },
];

export const CARD_IDS = Object.fromEntries(CARD_REGISTRY.map((c) => [c.id.toUpperCase().replace(/[^A-Z0-9]/g, '_'), c.id]));

export const CARDS = Object.fromEntries(CARD_REGISTRY.map((c) => [c.id, c]));
