/** Auto-generated card art manifest — run scripts/split-card-sheet.py */

/** @type {Record<string, string>} */
export const CARD_ART_URLS = {
  "backpedal": "./assets/cards/control/backpedal.webp",
  "blind": "./assets/cards/control/blind.webp",
  "blizzard": "./assets/cards/control/blizzard.webp",
  "confusion": "./assets/cards/control/confusion.webp",
  "deep_freeze": "./assets/cards/control/deep_freeze.webp",
  "demote": "./assets/cards/control/demote.webp",
  "panic": "./assets/cards/control/panic.webp",
  "press": "./assets/cards/control/press.webp",
  "root": "./assets/cards/control/root.webp",
  "shockwave": "./assets/cards/control/shockwave.webp",
  "snowball": "./assets/cards/control/snowball.webp",
  "tangle": "./assets/cards/control/tangle.webp",
  "aegis": "./assets/cards/defense/aegis.webp",
  "anchor": "./assets/cards/defense/anchor.webp",
  "backrank_protection": "./assets/cards/defense/backrank_protection.webp",
  "barrier": "./assets/cards/defense/barrier.webp",
  "bulwark": "./assets/cards/defense/bulwark.webp",
  "darkness": "./assets/cards/defense/darkness.webp",
  "iron_will": "./assets/cards/defense/iron_will.webp",
  "rally": "./assets/cards/defense/rally.webp",
  "revive": "./assets/cards/defense/revive.webp",
  "sanctuary": "./assets/cards/defense/sanctuary.webp",
  "stall": "./assets/cards/defense/stall.webp",
  "ward": "./assets/cards/defense/ward.webp",
  "backstep": "./assets/cards/movement/backstep.webp",
  "berserk": "./assets/cards/movement/berserk.webp",
  "bishops_mark": "./assets/cards/movement/bishops_mark.webp",
  "call_forward": "./assets/cards/movement/call_forward.webp",
  "chameleon": "./assets/cards/movement/chameleon.webp",
  "deport": "./assets/cards/movement/deport.webp",
  "displacement": "./assets/cards/movement/displacement.webp",
  "hostile_swap": "./assets/cards/movement/hostile_swap.webp",
  "leapfrog": "./assets/cards/movement/leapfrog.webp",
  "long_step": "./assets/cards/movement/long_step.webp",
  "magnet": "./assets/cards/movement/magnet.webp",
  "nudge": "./assets/cards/movement/nudge.webp",
  "quick_march": "./assets/cards/movement/quick_march.webp",
  "random_teleport": "./assets/cards/movement/random_teleport.webp",
  "recall": "./assets/cards/movement/recall.webp",
  "repel": "./assets/cards/movement/repel.webp",
  "retreat": "./assets/cards/movement/retreat.webp",
  "rooks_mark": "./assets/cards/movement/rooks_mark.webp",
  "scatter": "./assets/cards/movement/scatter.webp",
  "shadow_swap": "./assets/cards/movement/shadow_swap.webp",
  "sidestep": "./assets/cards/movement/sidestep.webp",
  "teleport": "./assets/cards/movement/teleport.webp",
  "bounty": "./assets/cards/special/bounty.webp",
  "butterfly": "./assets/cards/special/butterfly.webp",
  "clone": "./assets/cards/special/clone.webp",
  "collapse": "./assets/cards/special/collapse.webp",
  "constitution": "./assets/cards/special/constitution.webp",
  "create_foe": "./assets/cards/special/create_foe.webp",
  "crown": "./assets/cards/special/crown.webp",
  "dominion": "./assets/cards/special/dominion.webp",
  "earthquake": "./assets/cards/special/earthquake.webp",
  "fusion": "./assets/cards/special/fusion.webp",
  "hibernation": "./assets/cards/special/hibernation.webp",
  "ignore": "./assets/cards/special/ignore.webp",
  "last_king": "./assets/cards/special/last_king.webp",
  "link_fate": "./assets/cards/special/link_fate.webp",
  "mind_control": "./assets/cards/special/mind_control.webp",
  "offering": "./assets/cards/special/offering.webp",
  "purify": "./assets/cards/special/purify.webp",
  "trickster": "./assets/cards/special/trickster.webp",
  "counterspell": "./assets/cards/trap/counterspell.webp",
  "deflect": "./assets/cards/trap/deflect.webp",
  "landmine": "./assets/cards/trap/landmine.webp",
  "last_stand": "./assets/cards/trap/last_stand.webp",
  "quicksand": "./assets/cards/trap/quicksand.webp",
  "vengeance": "./assets/cards/trap/vengeance.webp",
  "backstab": "./assets/cards/attack/backstab.webp",
  "bomb": "./assets/cards/attack/bomb.webp",
  "chain_lightning": "./assets/cards/attack/chain_lightning.webp",
  "coin_flip": "./assets/cards/attack/coin_flip.webp",
  "cryo_bolt": "./assets/cards/attack/cryo_bolt.webp",
  "cull": "./assets/cards/attack/cull.webp",
  "duel": "./assets/cards/attack/duel.webp",
  "execution": "./assets/cards/attack/execution.webp",
  "poison": "./assets/cards/attack/poison.webp",
  "pyromancy": "./assets/cards/attack/pyromancy.webp",
  "sacrifice": "./assets/cards/attack/sacrifice.webp",
  "shatter": "./assets/cards/attack/shatter.webp",
  "snipe": "./assets/cards/attack/snipe.webp",
  "stab": "./assets/cards/attack/stab.webp"
};

/** @param {string} id */
export function cardArtUrl(id) {
  return CARD_ART_URLS[id] || null;
}

/** @param {string} id */
export function hasCardArt(id) {
  return id in CARD_ART_URLS;
}
