/** Auto-generated card registry — do not edit by hand; run scripts/generate-cards.py */

export const CARD_PLAY_MODES = {
  INSTANT: "instant",
  FRIENDLY: "friendly",
  ENEMY: "enemy",
  EMPTY: "empty",
  F_EMPTY: "f_empty",
  F_F: "f_f",
  F_E: "f_e",
  F_E_ADJ: "f_e_adj",
  E_EMPTY: "e_empty",
  E_E_ADJ: "e_e_adj",
  F_F_ADJ: "f_f_adj",
  DIAGONAL: "diagonal",
  ANY_PIECE: "any_piece",
  ANY_SQUARE: "any_square",
  EMPTY_EMPTY: "empty_empty",
  DISCARD_PICK: "discard_pick",
};

export const CARD_REGISTRY = [
  { id: "nudge", name: "Nudge", desc: "Displace one of your pieces 1 square to an adjacent empty dark square.", rarity: "common", weight: 8, mode: "f_empty", effect: "nudge" },
  { id: "aegis", name: "Aegis", desc: "Shield a piece — it cannot be captured for 2 turns.", rarity: "common", weight: 7, mode: "friendly", effect: "shield_2" },
  { id: "bolt", name: "Forward Bolt", desc: "Eliminate the first enemy piece directly ahead along your piece's forward diagonal.", rarity: "uncommon", weight: 6, mode: "diagonal", effect: "forward_bolt" },
  { id: "frost", name: "Frost Bind", desc: "Freeze an enemy piece — it cannot move on its owner's next turn.", rarity: "uncommon", weight: 6, mode: "enemy", effect: "freeze_1" },
  { id: "retreat", name: "Retreat Ward", desc: "Grant a piece backward movement for 3 turns.", rarity: "common", weight: 6, mode: "friendly", effect: "retreat_3" },
  { id: "crown", name: "Royal Decree", desc: "Instantly crown one of your pieces (king movement).", rarity: "rare", weight: 4, mode: "friendly", effect: "crown" },
  { id: "swap", name: "Shadow Swap", desc: "Swap positions of two of your pieces.", rarity: "uncommon", weight: 5, mode: "f_f", effect: "swap_friendly" },
  { id: "double", name: "Quick March", desc: "After your normal move, move the same piece again (non-capture step).", rarity: "rare", weight: 3, mode: "instant", effect: "quick_march" },
  { id: "gem_cache", name: "Gem Cache", desc: "Gain 20 gems immediately.", rarity: "common", weight: 7, mode: "instant", effect: "gems_20" },
  { id: "shatter", name: "Shatter", desc: "Destroy any enemy piece on the board (not shielded).", rarity: "epic", weight: 2, mode: "enemy", effect: "destroy_unshielded" },
  { id: "teleport", name: "Blink", desc: "Teleport your piece to any empty dark square within 2 steps (Chebyshev).", rarity: "rare", weight: 4, mode: "f_empty", effect: "blink_2" },
  { id: "long_step", name: "Long Step", desc: "Move one of your pieces 2 squares diagonally if the path is clear (no capture).", rarity: "uncommon", weight: 5, mode: "f_empty", effect: "long_step" },
  { id: "sidestep", name: "Sidestep", desc: "Move a piece 1 square horizontally onto an adjacent dark square.", rarity: "common", weight: 5, mode: "f_empty", effect: "sidestep" },
  { id: "chain_pull", name: "Chain Pull", desc: "Pull an adjacent enemy piece 1 square toward you into an empty dark square behind it.", rarity: "rare", weight: 3, mode: "friendly", effect: "chain_pull" },
  { id: "repel", name: "Repel", desc: "Push an adjacent enemy piece 1 square away if the landing square is empty.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "repel" },
  { id: "leapfrog", name: "Leapfrog", desc: "Jump your piece over a friendly piece to land on the empty square beyond.", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "leapfrog" },
  { id: "phase_walk", name: "Phase Walk", desc: "Move through one friendly piece to land on the empty square beyond it.", rarity: "rare", weight: 3, mode: "f_empty", effect: "phase_walk" },
  { id: "corner_hop", name: "Corner Hop", desc: "Teleport to any empty dark square in the opposite corner quadrant of the board.", rarity: "rare", weight: 3, mode: "f_empty", effect: "corner_hop" },
  { id: "anchor", name: "Anchor", desc: "Your piece cannot be moved by enemy cards for 2 turns (still moves on your turn).", rarity: "uncommon", weight: 4, mode: "friendly", effect: "anchor_2" },
  { id: "drift", name: "Drift", desc: "Slide a piece any number of empty squares along one diagonal until blocked.", rarity: "epic", weight: 2, mode: "f_empty", effect: "drift" },
  { id: "recall", name: "Recall", desc: "Return one of your pieces to any empty dark square in its starting row.", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "recall" },
  { id: "flank", name: "Flank", desc: "Move your piece to any empty dark square up to 3 steps away along a diagonal.", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "flank_3" },
  { id: "rooks_mark", name: "Rook's Mark", desc: "For 2 turns, a piece may slide along a rank or file over empty dark squares.", rarity: "rare", weight: 3, mode: "friendly", effect: "rook_2" },
  { id: "bishops_mark", name: "Bishop's Mark", desc: "For 2 turns, a piece may slide along either diagonal over empty dark squares.", rarity: "rare", weight: 3, mode: "friendly", effect: "bishop_2" },
  { id: "pawns_zeal", name: "Pawn's Zeal", desc: "A non-king takes one extra forward step this turn after your main move.", rarity: "common", weight: 4, mode: "friendly", effect: "pawn_zeal" },
  { id: "overrun", name: "Overrun", desc: "After a capture this turn, slide 1 more square forward along the same diagonal if empty.", rarity: "uncommon", weight: 4, mode: "instant", effect: "overrun" },
  { id: "cross_bolt", name: "Cross Bolt", desc: "Destroy the first enemy on both forward diagonals from your piece (if any).", rarity: "rare", weight: 3, mode: "friendly", effect: "cross_bolt" },
  { id: "snipe", name: "Snipe", desc: "Destroy an enemy exactly 2 squares away on a diagonal with nothing between.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "snipe" },
  { id: "mine", name: "Mine", desc: "Place a trap on an empty dark square; next enemy to land there is destroyed.", rarity: "uncommon", weight: 5, mode: "empty", effect: "mine" },
  { id: "detonate", name: "Detonate", desc: "Destroy your own piece to also destroy all adjacent enemies (not shielded).", rarity: "rare", weight: 3, mode: "friendly", effect: "detonate" },
  { id: "ricochet", name: "Ricochet", desc: "Arm your next capture to also remove an enemy 2 squares behind the captured piece.", rarity: "rare", weight: 3, mode: "instant", effect: "ricochet" },
  { id: "duel", name: "Duel", desc: "Choose your piece and an adjacent enemy; both are destroyed unless shielded.", rarity: "uncommon", weight: 4, mode: "f_e_adj", effect: "duel" },
  { id: "execution", name: "Execution", desc: "Destroy an enemy piece that has no legal moves.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "execution" },
  { id: "cull", name: "Cull", desc: "Destroy the weakest enemy (non-king preferred, fewest escape squares).", rarity: "rare", weight: 3, mode: "instant", effect: "cull" },
  { id: "hunters_mark", name: "Hunter's Mark", desc: "Mark an enemy; your next capture may jump to it from 2 squares away.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "hunters_mark" },
  { id: "venom", name: "Venom", desc: "Enemy takes 1 damage; 2 damage destroys it (shield blocks 1 tick).", rarity: "common", weight: 5, mode: "enemy", effect: "venom" },
  { id: "gravity_well", name: "Gravity Well", desc: "Pull all enemies adjacent to a square 1 step toward that square.", rarity: "rare", weight: 3, mode: "empty", effect: "gravity_well" },
  { id: "spear_thrust", name: "Spear Thrust", desc: "Destroy the first enemy along a rank or file from your piece.", rarity: "uncommon", weight: 4, mode: "f_empty", effect: "spear_thrust" },
  { id: "backstab", name: "Backstab", desc: "Destroy an enemy behind your piece on a backward diagonal if adjacent.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "backstab" },
  { id: "sacrifice", name: "Sacrifice", desc: "Destroy one of your men to destroy any enemy man (not kings).", rarity: "uncommon", weight: 4, mode: "f_e", effect: "sacrifice" },
  { id: "bulwark", name: "Bulwark", desc: "All your pieces on one diagonal line gain shield for 1 turn.", rarity: "rare", weight: 3, mode: "friendly", effect: "bulwark" },
  { id: "mirror_shield", name: "Mirror Shield", desc: "Next enemy spell on this piece reflects to a random enemy.", rarity: "epic", weight: 2, mode: "friendly", effect: "mirror_shield" },
  { id: "phalanx", name: "Phalanx", desc: "Two adjacent friendly pieces share protection — both must be jumped together.", rarity: "rare", weight: 3, mode: "f_f_adj", effect: "phalanx" },
  { id: "sanctuary", name: "Sanctuary", desc: "Friendly pieces on 4 adjacent dark squares to a point cannot be captured for 1 turn.", rarity: "rare", weight: 3, mode: "empty", effect: "sanctuary" },
  { id: "last_stand", name: "Last Stand", desc: "If this piece would be captured this turn, it survives with shield for 1 turn instead.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "last_stand" },
  { id: "decoy", name: "Decoy", desc: "Place a decoy on an empty dark square; blocks one enemy move then vanishes.", rarity: "common", weight: 5, mode: "empty", effect: "decoy" },
  { id: "iron_will", name: "Iron Will", desc: "A frozen or rooted friendly piece may move once (consumes debuff).", rarity: "common", weight: 5, mode: "friendly", effect: "iron_will" },
  { id: "revive", name: "Revive", desc: "Return a captured man to any empty square in your back 3 rows.", rarity: "epic", weight: 2, mode: "empty", effect: "revive" },
  { id: "ghost_guard", name: "Ghost Guard", desc: "When a friendly piece is captured, its square blocks enemies for 2 turns.", rarity: "rare", weight: 3, mode: "friendly", effect: "ghost_guard" },
  { id: "fortify", name: "Fortify", desc: "Piece is immobile and invulnerable for 2 turns, then gains shield for 1 turn.", rarity: "rare", weight: 3, mode: "friendly", effect: "fortify" },
  { id: "deep_freeze", name: "Deep Freeze", desc: "Enemy cannot move on its next turn.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "freeze_2" },
  { id: "root", name: "Root", desc: "Enemy cannot jump or capture on its next turn (can still step).", rarity: "uncommon", weight: 4, mode: "enemy", effect: "root_2" },
  { id: "backpedal", name: "Forced Retreat", desc: "Enemy can only move backward for 2 turns.", rarity: "uncommon", weight: 5, mode: "enemy", effect: "reverse_only_2" },
  { id: "slow", name: "Slow", desc: "Enemy kings move like men for 2 turns.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "slow_2" },
  { id: "blind", name: "Blind", desc: "Opponent cannot play cards on their next turn.", rarity: "rare", weight: 3, mode: "instant", effect: "blind" },
  { id: "confusion", name: "Confusion", desc: "On opponent's next turn, their move is chosen randomly.", rarity: "rare", weight: 3, mode: "instant", effect: "confusion" },
  { id: "silence", name: "Silence", desc: "Suppress knight/retreat/bishop/rook movement on an enemy for 3 turns.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "silence_3" },
  { id: "rust", name: "Rust", desc: "Target enemy cannot be crowned for the rest of the game.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "rust" },
  { id: "hex", name: "Hex", desc: "Marked enemy cannot receive buffs for 3 turns.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "hex_3" },
  { id: "tangle", name: "Tangle", desc: "Swap two adjacent enemies and freeze both for 1 turn.", rarity: "rare", weight: 3, mode: "e_e_adj", effect: "tangle" },
  { id: "fog", name: "Fog", desc: "One friendly piece is harder for the AI to target for 2 turns.", rarity: "common", weight: 5, mode: "friendly", effect: "fog_2" },
  { id: "panic", name: "Panic", desc: "Force an enemy man to step backward on its owner's next turn if possible.", rarity: "uncommon", weight: 4, mode: "enemy", effect: "panic" },
  { id: "bribery", name: "Bribery", desc: "Steal up to 15 gems from opponent.", rarity: "uncommon", weight: 4, mode: "instant", effect: "bribery_15" },
  { id: "bishops_sigil", name: "Bishop's Sigil", desc: "Piece slides diagonally any distance over empties for its next 2 moves.", rarity: "rare", weight: 3, mode: "friendly", effect: "bishop_3" },
  { id: "rooks_sigil", name: "Rook's Sigil", desc: "Piece slides along rank/file over empties for its next 2 moves.", rarity: "rare", weight: 3, mode: "friendly", effect: "rook_3" },
  { id: "demote", name: "Demote", desc: "Turn an enemy king back into a man.", rarity: "epic", weight: 2, mode: "enemy", effect: "demote" },
  { id: "promote_zone", name: "Promote Zone", desc: "Treat your piece as on the promotion row for movement this turn.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "promote_zone" },
  { id: "twin_soul", name: "Twin Soul", desc: "Split a man into two tokens on adjacent squares; linked fate.", rarity: "epic", weight: 2, mode: "friendly", effect: "twin_soul" },
  { id: "fusion", name: "Fusion", desc: "Merge two adjacent friendly men into one super-man (2-step non-capture).", rarity: "rare", weight: 3, mode: "f_f_adj", effect: "fusion" },
  { id: "chameleon", name: "Chameleon", desc: "Copy any piece's movement tags on the board for 2 turns.", rarity: "rare", weight: 3, mode: "any_piece", effect: "chameleon" },
  { id: "wraith_form", name: "Wraith Form", desc: "Piece passes through enemies for 2 turns (no capture while passing).", rarity: "rare", weight: 3, mode: "friendly", effect: "wraith_2" },
  { id: "stone_form", name: "Stone Form", desc: "Piece becomes a king immediately but cannot capture for 2 turns.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "stone_form" },
  { id: "obstacle", name: "Obstacle", desc: "Mark a light square as permanently impassable.", rarity: "uncommon", weight: 4, mode: "any_square", effect: "obstacle" },
  { id: "bridge", name: "Bridge", desc: "Link two empty dark squares; either can be entered from the other.", rarity: "rare", weight: 3, mode: "empty_empty", effect: "bridge" },
  { id: "quicksand", name: "Quicksand", desc: "Empty dark square freezes the next piece that ends a turn there.", rarity: "uncommon", weight: 4, mode: "empty", effect: "quicksand" },
  { id: "sanctified_tile", name: "Sanctified Tile", desc: "Friendly pieces entering this dark square are crowned.", rarity: "rare", weight: 3, mode: "empty", effect: "sanctified" },
  { id: "warp_gate", name: "Warp Gate", desc: "Link two empty dark squares for instant travel between them.", rarity: "rare", weight: 3, mode: "empty_empty", effect: "warp_gate" },
  { id: "collapse", name: "Collapse", desc: "Remove a dark square from play; piece on it moves to nearest empty dark square.", rarity: "epic", weight: 2, mode: "empty", effect: "collapse" },
  { id: "mirror_board", name: "Mirror Board", desc: "Confuse the AI's targeting for its next turn.", rarity: "common", weight: 5, mode: "instant", effect: "mirror_board" },
  { id: "darkness", name: "Darkness", desc: "Pieces on 4 dark squares around a point cannot be targeted by ranged spells for 2 turns.", rarity: "rare", weight: 3, mode: "empty", effect: "darkness" },
  { id: "highlight_path", name: "Highlight Path", desc: "Reduce AI strength slightly for 2 turns (reveals intent).", rarity: "common", weight: 5, mode: "instant", effect: "highlight_path" },
  { id: "earthquake", name: "Earthquake", desc: "All pieces shift 1 square toward board center if possible.", rarity: "epic", weight: 2, mode: "instant", effect: "earthquake" },
  { id: "prospect", name: "Prospect", desc: "Gain 10 gems now and 10 more at the start of your next turn.", rarity: "common", weight: 6, mode: "instant", effect: "prospect" },
  { id: "tax", name: "Tax", desc: "Opponent loses 10 gems; you gain 5.", rarity: "uncommon", weight: 4, mode: "instant", effect: "tax" },
  { id: "gamble", name: "Gamble", desc: "Pay 15 gems; draw 2 cards.", rarity: "uncommon", weight: 4, mode: "instant", effect: "gamble" },
  { id: "haggle", name: "Haggle", desc: "Your next card draw costs 5 gems instead of 10.", rarity: "common", weight: 5, mode: "instant", effect: "haggle" },
  { id: "recycle", name: "Recycle", desc: "Discard 1 card from hand, draw 2 cards.", rarity: "common", weight: 5, mode: "discard_pick", effect: "recycle" },
  { id: "scout", name: "Scout", desc: "Look at 3 random cards from the pool; add one to your hand.", rarity: "uncommon", weight: 4, mode: "instant", effect: "scout" },
  { id: "forge", name: "Forge", desc: "Discard 2 cards to add a random rare or epic to your hand.", rarity: "rare", weight: 3, mode: "instant", effect: "forge" },
  { id: "heist", name: "Heist", desc: "Steal a random card from opponent's hand.", rarity: "rare", weight: 3, mode: "instant", effect: "heist" },
  { id: "donate", name: "Donate", desc: "Give opponent 20 gems; you draw 2 cards.", rarity: "common", weight: 5, mode: "instant", effect: "donate" },
  { id: "interest", name: "Interest", desc: "Gain gems equal to half your total (max 25).", rarity: "uncommon", weight: 4, mode: "instant", effect: "interest" },
  { id: "bankrupt", name: "Bankrupt", desc: "Both players lose half their gems.", rarity: "rare", weight: 3, mode: "instant", effect: "bankrupt" },
  { id: "coupon", name: "Coupon", desc: "Your next card draw is free.", rarity: "common", weight: 5, mode: "instant", effect: "coupon" },
  { id: "hand_expand", name: "Hand Expand", desc: "Your hand limit becomes 8 for the rest of the game.", rarity: "rare", weight: 3, mode: "instant", effect: "hand_expand" },
  { id: "mulligan", name: "Mulligan", desc: "Discard your hand and draw the same number of new cards.", rarity: "uncommon", weight: 4, mode: "instant", effect: "mulligan" },
  { id: "hostile_swap", name: "Hostile Swap", desc: "Swap one of your pieces with an enemy (both unshielded).", rarity: "epic", weight: 2, mode: "f_e", effect: "hostile_swap" },
  { id: "possession", name: "Possession", desc: "Control an enemy piece for its owner's next move only.", rarity: "epic", weight: 2, mode: "enemy", effect: "possession" },
  { id: "identity_theft", name: "Identity Theft", desc: "Your piece copies an enemy's movement tags for 3 turns.", rarity: "rare", weight: 3, mode: "f_e", effect: "identity_theft" },
  { id: "bait_switch", name: "Bait and Switch", desc: "Swap an enemy with an empty square up to 2 steps away.", rarity: "rare", weight: 3, mode: "e_empty", effect: "bait_switch" },
  { id: "mirror_move", name: "Mirror Move", desc: "After opponent moves, copy their move pattern with your piece if legal.", rarity: "rare", weight: 3, mode: "instant", effect: "mirror_move" },
  { id: "time_slip", name: "Time Slip", desc: "Undo your last checkers move (once per game).", rarity: "epic", weight: 1, mode: "instant", effect: "time_slip" },
  { id: "parallel", name: "Parallel", desc: "Play one additional card this turn.", rarity: "rare", weight: 3, mode: "instant", effect: "parallel" },
  { id: "counterspell", name: "Counterspell", desc: "Cancel the next enemy card played.", rarity: "uncommon", weight: 5, mode: "instant", effect: "counterspell" },
  { id: "echo", name: "Echo", desc: "Repeat the last card you played.", rarity: "rare", weight: 3, mode: "instant", effect: "echo" },
  { id: "roulette", name: "Roulette", desc: "Random card effect hits a random valid target.", rarity: "epic", weight: 2, mode: "instant", effect: "roulette" },
  { id: "blizzard", name: "Blizzard", desc: "Freeze up to 3 enemy men along a diagonal line you choose.", rarity: "rare", weight: 3, mode: "friendly", effect: "blizzard" },
  { id: "fireline", name: "Fireline", desc: "Forward Bolt hits every enemy along one forward diagonal.", rarity: "rare", weight: 3, mode: "friendly", effect: "fireline" },
  { id: "sanctuary_pulse", name: "Sanctuary Pulse", desc: "Shield all your pieces in your back row for 1 turn.", rarity: "uncommon", weight: 4, mode: "instant", effect: "sanctuary_pulse" },
  { id: "mass_nudge", name: "Mass Nudge", desc: "Move up to 2 friendly pieces 1 square each (adjacent empty).", rarity: "uncommon", weight: 4, mode: "instant", effect: "mass_nudge" },
  { id: "chain_lightning", name: "Chain Lightning", desc: "Destroy first enemy in a line; chains up to 3 times.", rarity: "epic", weight: 2, mode: "friendly", effect: "chain_lightning" },
  { id: "vacuum", name: "Vacuum", desc: "Pull all pieces 1 step toward a chosen empty dark square.", rarity: "rare", weight: 3, mode: "empty", effect: "vacuum" },
  { id: "scatter", name: "Scatter", desc: "Push every piece adjacent to a square 1 step away radially.", rarity: "rare", weight: 3, mode: "empty", effect: "scatter" },
  { id: "dominion", name: "Dominion", desc: "All your men may move backward this turn.", rarity: "uncommon", weight: 4, mode: "instant", effect: "dominion" },
  { id: "rally", name: "Rally", desc: "All pieces adjacent to a friendly piece gain retreat for 1 turn.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "rally" },
  { id: "coronation_day", name: "Coronation Day", desc: "All your men on the promotion row become kings.", rarity: "epic", weight: 2, mode: "instant", effect: "coronation_day" },
  { id: "exile_king", name: "Exile King", desc: "Teleport enemy king to a random empty square on their back row.", rarity: "epic", weight: 2, mode: "enemy", effect: "exile_king" },
  { id: "regicide", name: "Regicide", desc: "If you capture a king this turn, gain 30 gems.", rarity: "rare", weight: 3, mode: "instant", effect: "regicide" },
  { id: "constitution", name: "Constitution", desc: "Your kings cannot be destroyed by non-capture effects for 5 turns.", rarity: "rare", weight: 3, mode: "instant", effect: "constitution" },
  { id: "last_king", name: "Last King", desc: "If you have only 1 piece, it becomes a king with shield for 2 turns.", rarity: "epic", weight: 2, mode: "instant", effect: "last_king" },
  { id: "succession", name: "Succession", desc: "When your king is captured, a chosen man becomes king instantly.", rarity: "rare", weight: 3, mode: "friendly", effect: "succession" },
  { id: "coin_flip", name: "Coin Flip", desc: "50% destroy random enemy; 50% destroy random friendly.", rarity: "rare", weight: 3, mode: "instant", effect: "coin_flip" },
  { id: "butterfly_effect", name: "Butterfly Effect", desc: "Shuffle pieces on the 4 center dark squares randomly.", rarity: "rare", weight: 3, mode: "instant", effect: "butterfly" },
  { id: "rules_lawyer", name: "Rules Lawyer", desc: "Jumps are optional for you this turn (not mandatory).", rarity: "uncommon", weight: 4, mode: "instant", effect: "rules_lawyer" },
  { id: "pocket_dimension", name: "Pocket Dimension", desc: "Remove a friendly piece for 1 turn; it returns to the same square.", rarity: "rare", weight: 3, mode: "friendly", effect: "pocket" },
  { id: "uno_reverse", name: "Uno Reverse", desc: "Opponent must capture with a specific piece if possible next turn.", rarity: "rare", weight: 3, mode: "enemy", effect: "uno_reverse" },
  { id: "krabby_patty", name: "Krabby Patty", desc: "Gain 5 gems. Delicious.", rarity: "common", weight: 6, mode: "instant", effect: "gems_5" },
  { id: "loading", name: "Loading…", desc: "Draw 1 card.", rarity: "common", weight: 6, mode: "instant", effect: "draw_1" },
  { id: "conduct", name: "Conduct", desc: "If you played a movement card this turn, your checker step may be 2 squares.", rarity: "uncommon", weight: 4, mode: "instant", effect: "conduct" },
  { id: "cryo_bolt", name: "Cryo Bolt", desc: "Forward Bolt on a frozen target breaks shield and destroys it.", rarity: "rare", weight: 3, mode: "diagonal", effect: "cryo_bolt" },
  { id: "shield_bash", name: "Shield Bash", desc: "A shielded piece moves 1 square and destroys adjacent unshielded enemy.", rarity: "uncommon", weight: 4, mode: "friendly", effect: "shield_bash" },
  { id: "bomb", name: "Bomb", desc: "Arm a friendly piece. The next time it moves, it explodes and destroys every piece on adjacent squares (including itself).", rarity: "legendary", weight: 1, mode: "friendly", effect: "bomb" }
];

export const CARD_IDS = Object.fromEntries(CARD_REGISTRY.map((c) => [c.id.toUpperCase().replace(/[^A-Z0-9]/g, '_'), c.id]));

export const CARDS = Object.fromEntries(CARD_REGISTRY.map((c) => [c.id, c]));
